/**
 * Checks an error against a predicate recursively.
 * This handles both `AggregateError` and `Error`.
 * This recursively checks against the `cause` property.
 */
declare function checkError(error: unknown, p: (error: unknown) => boolean, visited?: Set<unknown>): boolean;
export { checkError };
